    )
     u_ddr_phy_oclkdelay_cal
       (
    
    .prbs_ignore_first_byte           (prbs_ignore_first_byte),
    .prbs_ignore_last_bytes           (prbs_ignore_last_bytes),
    .complex_oclkdelay_calib_done   (complex_oclkdelay_calib_done),
    .dbg_oclkdelay_rd_data          (dbg_oclkdelay_rd_data[16*DRAM_WIDTH-1:0]),
    .dbg_phy_oclkdelay_cal          (dbg_phy_oclkdelay_cal[255:0]),
    .lim2init_write_request         (lim2init_write_request),
    .lim_done                       (lim_done),
    .oclk_calib_resume              (oclk_calib_resume),
    .oclk_prech_req                 (oclk_prech_req),
    .oclkdelay_calib_cnt            (oclkdelay_calib_cnt[DQS_CNT_WIDTH:0]),
    .oclkdelay_calib_done           (oclkdelay_calib_done),
    .po_en_stg23                    (po_en_stg23),
    .po_stg23_incdec                (po_stg23_incdec),
    .po_stg23_sel                   (po_stg23_sel),
    .psen                           (psen),
    .psincdec                       (psincdec),
    .wrlvl_final                    (wrlvl_final),
    .rd_victim_sel                  (complex_ocal_rd_victim_sel),
    .ocal_num_samples_done_r        (complex_ocal_num_samples_done_r),
    .complex_wrlvl_final            (complex_wrlvl_final),
    .poc_error                      (poc_error),
    
    .clk                            (clk),
    .complex_oclkdelay_calib_start  (complex_oclkdelay_calib_start_w),
    .metaQ                          (pd_out),
    
    .po_counter_read_val            (po_counter_read_val),
    .oclkdelay_calib_start          (oclkdelay_calib_start),
    .oclkdelay_init_val             (oclkdelay_init_val[5:0]),
    .poc_sample_pd                  (poc_sample_pd),
    .phy_rddata                     (phy_rddata[2*nCK_PER_CLK*DQ_WIDTH-1:0]),
    .phy_rddata_en                  (phy_rddata_en),
    .prbs_o                         (prbs_o[2*nCK_PER_CLK*DQ_WIDTH-1:0]),
    .prech_done                     (prech_done),
    .psdone                         (psdone),
    .rst                            (rst),
    .wl_po_fine_cnt                 (wl_po_fine_cnt[6*DQS_WIDTH-1:0]),
    .ocal_num_samples_inc           (complex_ocal_num_samples_inc),
    .oclkdelay_center_calib_start   (oclkdelay_center_calib_start),
    .oclk_center_write_resume       (oclk_center_write_resume),
    .oclkdelay_center_calib_done    (oclkdelay_center_calib_done),
    .dbg_ocd_lim                    (dbg_ocd_lim),
    .dbg_poc                         (dbg_poc[1023:0]) );