  always @(*) begin
    dbg_poc_r[99:0] = 'b0;
    dbg_poc_r[1023:900] = 'b0;
    dbg_poc_r[0] = mmcm_edge_detect_rdy;
    dbg_poc_r[1] = mmcm_edge_detect_done;
    dbg_poc_r[2] = ktap_at_right_edge;
    dbg_poc_r[3] = ktap_at_left_edge;
    dbg_poc_r[4] = mmcm_lbclk_edge_aligned;
    dbg_poc_r[5] = poc_backup;
    dbg_poc_r[6+:SMWIDTH] = sm;
    dbg_poc_r[10+:TAPCNTRWIDTH] = tap;
    dbg_poc_r[20+:TAPCNTRWIDTH] = run;
    dbg_poc_r[30] = run_end;
    dbg_poc_r[31] = run_polarity;
    dbg_poc_r[32] = run_too_small;
    dbg_poc_r[33+:SAMPCNTRWIDTH] = samp_cntr;
    dbg_poc_r[49+:SAMPCNTRWIDTH+1] = samps_hi;
    dbg_poc_r[66+:SAMPCNTRWIDTH+1] = samps_hi_held;
    dbg_poc_r[83] = samps_zero;
    dbg_poc_r[84] = samps_one;
    dbg_poc_r[86:85] = run_ends;
    dbg_poc_r[87+:TAPCNTRWIDTH+2] = diff;
  end 