    .INIT_B                 ( 36'h000000000     ),
    .WRITE_MODE_A           ( "WRITE_FIRST"     ),
    .WRITE_MODE_B           ( "WRITE_FIRST"     ),
    .SRVAL_B                ( 36'h000000000     ))
  u_sram5  (
    .REGCEA ( 1'd0                              ),
    .CLKA   ( i_clk                             ),
    .ENB    ( 1'd0                              ),
    .RSTB   ( 1'd0                              ),
    .CLKB   ( 1'd0                              ),
    .REGCEB ( 1'd0                              ),
    .RSTA   ( 1'd0                              ),
    .ENA    ( 1'd1                              ),
    .DIPA   ( 4'd0                              ),
    .WEA    ( wea_b1[7:4]                       ),
    .DOA    ( read_data_b1[63:32]               ),
    .ADDRA  ( {i_address[8:0], 5'd0}            ),
    .ADDRB  ( 14'd0                             ),
    .DIB    ( 32'd0                             ),
    .DOPA   (                                   ),
    .DIPB   ( 4'd0                              ),
    .DOPB   (                                   ),