
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jul  6 2023 11:15:21 IST (Jul  6 2023 05:45:21 UTC)

// Verification Directory fv/decoder2to4 

module decoder2to4(a, b, en, i0, i1, i2, i3);
  input a, b, en;
  output i0, i1, i2, i3;
  wire a, b, en;
  wire i0, i1, i2, i3;
  wire n_0, n_3;
  NOR2XL g83(.A (n_3), .B (b), .Y (i0));
  NOR2BXL g85(.AN (b), .B (n_3), .Y (i1));
  NOR2XL g86(.A (n_0), .B (b), .Y (i2));
  NOR2BXL g84(.AN (b), .B (n_0), .Y (i3));
  NAND2XL g87(.A (en), .B (a), .Y (n_0));
  NAND2BXL g88(.AN (a), .B (en), .Y (n_3));
endmodule

