reg     [ 10: 0] MonAReg ;
wire    [  8: 0] MonARegAddrInc;
wire             MonARegAddrIncAccessingRAM;
reg     [ 31: 0] MonDReg ;
reg              avalon_ociram_readdata_ready ;
wire             avalon_ram_wr;
wire    [ 31: 0] cfgrom_readdata;
reg              jtag_ram_access ;
reg              jtag_ram_rd ;
reg              jtag_ram_rd_d1 ;
reg              jtag_ram_wr ;
reg              jtag_rd ;
reg              jtag_rd_d1 ;
wire    [  7: 0] ociram_addr;
wire    [  3: 0] ociram_byteenable;
wire    [ 31: 0] ociram_readdata;
wire             ociram_reset_req;
wire    [ 31: 0] ociram_wr_data;
wire             ociram_wr_en;
reg              waitrequest ;